[2025-01-24T04:02:46.137+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T04:02:46.142+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.extract_gz_task scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-24T04:02:46.144+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.extract_gz_task scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-24T04:02:46.144+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-24T04:02:46.148+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_gz_task> on 2025-01-22 00:00:00+00:00
[2025-01-24T04:02:46.151+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-24T04:02:46.152+0000] {standard_task_runner.py:72} INFO - Started process 81 to run task
[2025-01-24T04:02:46.152+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'extract_gz_task', 'scheduled__2025-01-22T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/GCP Project/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmps5o4n1ex']
[2025-01-24T04:02:46.153+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask extract_gz_task
[2025-01-24T04:02:46.171+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.extract_gz_task scheduled__2025-01-22T00:00:00+00:00 [running]> on host 3d9406b7dd3e
[2025-01-24T04:02:46.200+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='extract_gz_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-22T00:00:00+00:00'
[2025-01-24T04:02:46.201+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T04:02:46.476+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-24T04:02:46.483+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T04:02:46.487+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=extract_gz_task, run_id=scheduled__2025-01-22T00:00:00+00:00, execution_date=20250122T000000, start_date=20250124T040246, end_date=20250124T040246
[2025-01-24T04:02:46.511+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-24T04:02:46.519+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-24T04:02:46.520+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
