[2025-01-24T07:01:54.644+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T07:01:54.649+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2025-01-24T06:54:31.432507+00:00 [queued]>
[2025-01-24T07:01:54.652+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2025-01-24T06:54:31.432507+00:00 [queued]>
[2025-01-24T07:01:54.652+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-24T07:01:54.656+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2025-01-24 06:54:31.432507+00:00
[2025-01-24T07:01:54.659+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=88) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-24T07:01:54.659+0000] {standard_task_runner.py:72} INFO - Started process 89 to run task
[2025-01-24T07:01:54.659+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'manual__2025-01-24T06:54:31.432507+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/GCP Project/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp6_4uw634']
[2025-01-24T07:01:54.661+0000] {standard_task_runner.py:105} INFO - Job 48: Subtask local_to_gcs_task
[2025-01-24T07:01:54.674+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2025-01-24T06:54:31.432507+00:00 [running]> on host 22ff6bf154fe
[2025-01-24T07:01:54.699+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='local_to_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T06:54:31.432507+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T06:54:31.432507+00:00'
[2025-01-24T07:01:54.700+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T07:02:01.869+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-24T07:02:01.879+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T07:02:01.880+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, run_id=manual__2025-01-24T06:54:31.432507+00:00, execution_date=20250124T065431, start_date=20250124T070154, end_date=20250124T070201
[2025-01-24T07:02:01.908+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-24T07:02:01.921+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-24T07:02:01.921+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
