[2025-01-24T06:38:31.234+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T06:38:31.239+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2025-01-23T00:00:00+00:00 [queued]>
[2025-01-24T06:38:31.241+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2025-01-23T00:00:00+00:00 [queued]>
[2025-01-24T06:38:31.242+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-24T06:38:31.245+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): download_dataset_task> on 2025-01-23 00:00:00+00:00
[2025-01-24T06:38:31.248+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=66) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-24T06:38:31.249+0000] {standard_task_runner.py:72} INFO - Started process 67 to run task
[2025-01-24T06:38:31.249+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2025-01-23T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/GCP Project/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpk4j0ovrw']
[2025-01-24T06:38:31.250+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask download_dataset_task
[2025-01-24T06:38:31.269+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2025-01-23T00:00:00+00:00 [running]> on host 318629d7f412
[2025-01-24T06:38:31.295+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='download_dataset_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-23T00:00:00+00:00'
[2025-01-24T06:38:31.296+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T06:38:31.308+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-24T06:38:31.309+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'curl -sS -L --fail https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz > /opt/***/yellow_tripdata_2021-01.csv.gz']
[2025-01-24T06:38:31.313+0000] {subprocess.py:99} INFO - Output:
[2025-01-24T06:38:34.526+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-24T06:38:34.550+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T06:38:34.550+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, run_id=scheduled__2025-01-23T00:00:00+00:00, execution_date=20250123T000000, start_date=20250124T063831, end_date=20250124T063834
[2025-01-24T06:38:34.581+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-24T06:38:34.591+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-24T06:38:34.592+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
